# Netlify configuration for Family Recipe App
# This file configures Netlify to properly handle Next.js deployments

[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NEXT_TELEMETRY_DISABLED = "1"

# Handle client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
